# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enter Ophelia
repository: opheiko/opheiko.github.io
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is dedicated to Ophelia. 
  She was a very good cat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

collections:
    posts:
      name: Posts
      output: true
    cfd_nm:
      name: Computational Fluid Dynamics and Numerical Methods
      output: true
    chem:
      name: Chemistry and other science
      output: true
    ctrl:
      name: Control Theory
      output: true
    gfd:
      name: Geophysical Fluid Dynamics and Oceanography
      output: true
    ml_math:
      name: Machine Learning and Related Math
      output: true
    open_science:
      name: Open Science and other Open-Source Data
      output: true
    code:
      name: Code and Programming
      output: true


# Build settings
markdown: kramdown
theme: just-the-docs
#theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
github: [metadata]

#kramdown:
#    math-engine: katex

just_the_docs:
  collections:
    posts:
      name: Posts
      nav_fold: true
    cfd_nm:
      name: Computational Fluid Dynamics and Numerical Methods
      nav_fold: true
    chem:
      name: Chemistry and other science
      nav_fold: true
    ctrl:
      name: Control Theory
      nav_fold: true
    gfd:
      name: Geophysical Fluid Dynamics and Oceanography
      nav_fold: true
    ml_math:
      name: Machine Learning and Related Math
      nav_fold: true
    open_science:
      name: Open Science and other Open-Source Data
      nav_fold: true
    code:
      name: Code and Programming
      nav_fold: true


    
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/