title: Musings
description: Dedicated to Ophelia the Cat
remote_theme: pages-themes/minimal@v0.2.0
google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
